### ISSUE TITLE
`DecodeError` and `EncodeError` do not impl `std::error::Error`

### ISSUE THREAD

**Issue by EndilWayfare** [dylanhart/ulid-rs#30]
Hey, thanks for the excellent ULID implementation!

The error types already implement all the traits necessary to be std `Error`; all that would be needed is to add the empty impl.

Interop with the error handling ecosystem would be smoother if the _de facto_ `Error`s were recognized by the type system.

**Comment by dylanhart** [comment]
v0.4.1 pushed with the change!
