### ISSUE TITLE
Unexpected ordering

### ISSUE THREAD

**Issue by maxcountryman** [dylanhart/ulid-rs#39]
Hi there, I'm trying to write a test that demonstrates the ULID ordering promises but am seeing some unexpected behavior every few test runs or so:

```
[src/models/id.rs:141] &id_0 = Ulid(1972003866952799546420484161793439825);
[src/models/id.rs:142] &id_1 = Ulid(1972003866952020694265156341296371228);
thread 'models::id::tests::test_ordering_monotonic' panicked at 'assertion failed: id_0 < id_1'
```

Most of the time this assertion is true but sometimes it isn't. The test is simply constructing two ULIDs one after the other and then asserting.

**Comment by dylanhart** [comment]
This assertion is only valid when Ulid instances are created by [Generator](https://docs.rs/ulid/0.4.1/ulid/struct.Generator.html) since there is additional state that needs to be tracked in order to ensure that the ordering is valid.
