### ISSUE TITLE
to_str variable buffer size

### ISSUE THREAD

**Issue by WalterSmuts** [dylanhart/ulid-rs#67]
Hi,

Just wondering why you allow the user to specify the buffer `>=ULID_LEN`. Is there any situation where the user wants to supply a larger buffer than `ULID_LEN`? The tradeoff you're making is having the `to_str` API be fallible and forcing the user to supply their own buffer.

**Comment by dylanhart** [comment]
Yep, that's correct. I didn't think about that at the time.
